# Generated by Django 4.0.3 on 2022-03-23 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.AddField(
            model_name='post',
            name='caregorias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppBlog.categoria'),
            preserve_default=False,
        ),
    ]
