# Generated by Django 4.0.3 on 2022-03-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_remove_post_categorias_post_caregorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caregorias',
        ),
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(to='AppBlog.categoria'),
        ),
    ]
